version: "3.9"

services:
  discordtimefinder:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - discordtimefinder-network
    restart:
      always

networks:
  discordtimefinder-network:
